"""
ES7210 4-Channel Audio ADC Driver for MicroPython
I2C driver for the microphone input on the
Waveshare ESP32-S3-Touch-AMOLED-2.06.

This board has a dual-codec audio architecture:
  - ES7210 (this driver) → 4-ch ADC for dual MEMS microphone array
  - ES8311 (separate)    → DAC for speaker output

The ES7210 shares I2C address 0x40 with the TCA9554 GPIO expander.
MCLK is generated by PWM on GPIO16 at 256 * sample_rate.

Register values derived from Espressif esp-bsp and esp-adf es7210 drivers
for MCLK=4.096 MHz, Fs=16 kHz, slave mode, I2S 16-bit format.

Usage:
    from machine import I2C, Pin
    import board_config as BOARD
    from drivers.es7210 import ES7210

    i2c = I2C(0, sda=Pin(BOARD.I2C_SDA), scl=Pin(BOARD.I2C_SCL),
              freq=BOARD.I2C_FREQ)
    adc = ES7210(i2c)
    adc.init()                # Powers up ADC, starts MCLK, configures mics
    adc.set_mic_gain(24)      # 24 dB PGA gain on all channels
"""

import time
from machine import Pin, PWM

import board_config as BOARD


# ─── ES7210 Register Map ─────────────────────────────────────────
_REG_RESET       = 0x00  # Reset control / device enable
_REG_CLK_OFF     = 0x01  # ADC clock on/off per channel
_REG_MAINCLK     = 0x02  # ADC clock freq division (adc_div, doubler, dll)
_REG_MASTER_CLK  = 0x03  # MCLK source and SCLK division
_REG_LRCK_DIVH   = 0x04  # LRCK divider high byte
_REG_LRCK_DIVL   = 0x05  # LRCK divider low byte
_REG_POWER_DOWN  = 0x06  # Power down control (DLL)
_REG_OSR         = 0x07  # Oversampling ratio
_REG_MODE_CFG    = 0x08  # Master/slave mode, channel config
_REG_TIME_CTL0   = 0x09  # Chip initial state period
_REG_TIME_CTL1   = 0x0A  # Power-up state period
_REG_SDP_IF1     = 0x11  # I2S format + bit width
_REG_SDP_IF2     = 0x12  # TDM enable / pin state
_REG_AUTOMUTE    = 0x13  # Automute configuration
_REG_ADC34_MUTE  = 0x14  # ADC3/4 mute range
_REG_ADC12_MUTE  = 0x15  # ADC1/2 mute range
_REG_ALC_SEL     = 0x16  # ALC mode selection
_REG_ADC1_DVOL   = 0x1B  # ADC1 digital volume
_REG_ADC2_DVOL   = 0x1C  # ADC2 digital volume
_REG_ADC3_DVOL   = 0x1D  # ADC3 digital volume
_REG_ADC4_DVOL   = 0x1E  # ADC4 digital volume
_REG_ADC34_HPF2  = 0x20  # HPF coefficient for ADC3/4
_REG_ADC34_HPF1  = 0x21  # HPF coefficient for ADC3/4
_REG_ADC12_HPF2  = 0x22  # HPF coefficient for ADC1/2
_REG_ADC12_HPF1  = 0x23  # HPF coefficient for ADC1/2
_REG_ANALOG      = 0x40  # Analog power control
_REG_MIC12_BIAS  = 0x41  # MIC1/2 bias voltage
_REG_MIC34_BIAS  = 0x42  # MIC3/4 bias voltage
_REG_MIC1_GAIN   = 0x43  # MIC1 PGA gain
_REG_MIC2_GAIN   = 0x44  # MIC2 PGA gain
_REG_MIC3_GAIN   = 0x45  # MIC3 PGA gain
_REG_MIC4_GAIN   = 0x46  # MIC4 PGA gain
_REG_MIC1_PWR    = 0x47  # MIC1 power control
_REG_MIC2_PWR    = 0x48  # MIC2 power control
_REG_MIC3_PWR    = 0x49  # MIC3 power control
_REG_MIC4_PWR    = 0x4A  # MIC4 power control
_REG_MIC12_PWR   = 0x4B  # MIC1/2 bias + ADC + PGA power
_REG_MIC34_PWR   = 0x4C  # MIC3/4 bias + ADC + PGA power

# PGA gain table: dB → register code (bit[4] must be set = enable)
# Each step is ~3 dB: code 0=0dB, 1=3dB, ..., 8=24dB, ..., 14=37.5dB
_GAIN_TABLE = {
    0: 0x00,  3: 0x01,  6: 0x02,  9: 0x03,
    12: 0x04, 15: 0x05, 18: 0x06, 21: 0x07,
    24: 0x08, 27: 0x09, 30: 0x0A, 33: 0x0B,
    34: 0x0C, 36: 0x0D, 37: 0x0E,
}

# Clock coefficients for MCLK=4.096 MHz, Fs=16 kHz
# From Espressif esp-adf coeff_div table row 8:
# {4096000, 16000, ss_ds=0, adc_div=1, dll=1, doubler=1, osr=0x20,
#  mclk_src=0, lrck_h=0x01, lrck_l=0x00}
_CLK_ADC_DIV  = 0x01
_CLK_DLL      = 1
_CLK_DOUBLER  = 1
_CLK_OSR      = 0x20
_CLK_LRCK_H   = 0x01
_CLK_LRCK_L   = 0x00


class ES7210:
    """ES7210 4-channel audio ADC driver — microphone input."""

    def __init__(self, i2c, addr=None):
        self._i2c = i2c
        self._addr = addr or BOARD.ES7210_ADDR
        self._mclk_pwm = None
        self._powered = False

    # ─── Low-level I2C ────────────────────────────────────────────

    def _read_reg(self, reg):
        self._i2c.writeto(self._addr, bytes([reg]))
        return self._i2c.readfrom(self._addr, 1)[0]

    def _write_reg(self, reg, val):
        self._i2c.writeto(self._addr, bytes([reg, val & 0xFF]))

    def _update_reg(self, reg, mask, val):
        """Read-modify-write: clear bits in mask, OR in value."""
        cur = self._read_reg(reg)
        self._write_reg(reg, (cur & ~mask) | (val & mask))

    # ─── Initialization ───────────────────────────────────────────

    def init(self):
        """Full power-up: start MCLK, configure for 16 kHz stereo ADC.

        Register sequence follows Espressif esp-bsp es7210_config_codec().
        The dual MEMS mics are on MIC1 + MIC2 (standard I2S stereo,
        no TDM needed).
        """
        # 1. Start MCLK via PWM on GPIO16: 4.096 MHz
        self._mclk_pwm = PWM(Pin(BOARD.I2S_MCLK),
                             freq=BOARD.AUDIO_MCLK_FREQ,
                             duty_u16=32768)  # 50% duty
        time.sleep_ms(20)
        print(f"ES7210: MCLK started on GPIO{BOARD.I2S_MCLK} at {BOARD.AUDIO_MCLK_FREQ}Hz")

        # 2. Software reset
        self._write_reg(_REG_RESET, 0xFF)
        time.sleep_ms(10)
        self._write_reg(_REG_RESET, 0x32)
        time.sleep_ms(10)

        # 3. Timing control (chip init + power-up state periods)
        self._write_reg(_REG_TIME_CTL0, 0x30)
        self._write_reg(_REG_TIME_CTL1, 0x30)

        # 4. High-pass filter setup (remove DC offset from MEMS mics)
        self._write_reg(_REG_ADC12_HPF1, 0x2A)
        self._write_reg(_REG_ADC12_HPF2, 0x0A)
        self._write_reg(_REG_ADC34_HPF1, 0x2A)
        self._write_reg(_REG_ADC34_HPF2, 0x0A)

        # 5. I2S format: 16-bit, standard I2S (Philips), no TDM
        self._write_reg(_REG_SDP_IF1, 0x60)  # 16-bit, I2S normal
        self._write_reg(_REG_SDP_IF2, 0x00)  # No TDM (2-ch stereo)

        # 6. Analog power on
        self._write_reg(_REG_ANALOG, 0xC3)

        # 7. Microphone bias voltage (2.87V for MEMS mics)
        self._write_reg(_REG_MIC12_BIAS, 0x70)
        self._write_reg(_REG_MIC34_BIAS, 0x70)

        # 8. PGA gain (default 24 dB)
        gain_code = 0x10 | _GAIN_TABLE.get(BOARD.AUDIO_MIC_GAIN_DB, 0x08)
        self._write_reg(_REG_MIC1_GAIN, gain_code)
        self._write_reg(_REG_MIC2_GAIN, gain_code)
        self._write_reg(_REG_MIC3_GAIN, gain_code)
        self._write_reg(_REG_MIC4_GAIN, gain_code)

        # 9. Individual microphone power on
        self._write_reg(_REG_MIC1_PWR, 0x08)
        self._write_reg(_REG_MIC2_PWR, 0x08)
        self._write_reg(_REG_MIC3_PWR, 0x08)
        self._write_reg(_REG_MIC4_PWR, 0x08)

        # 10. Clock configuration for 16 kHz with MCLK = 4.096 MHz
        self._write_reg(_REG_OSR, _CLK_OSR)
        # REG02 = adc_div | (doubler << 6) | (dll << 7)
        reg02 = _CLK_ADC_DIV | (_CLK_DOUBLER << 6) | (_CLK_DLL << 7)
        self._write_reg(_REG_MAINCLK, reg02)
        self._write_reg(_REG_LRCK_DIVH, _CLK_LRCK_H)
        self._write_reg(_REG_LRCK_DIVL, _CLK_LRCK_L)

        # 11. Power up sequence
        self._write_reg(_REG_POWER_DOWN, 0x04)  # DLL power
        self._write_reg(_REG_MIC12_PWR, 0x0F)   # MIC1/2: bias+ADC+PGA power
        self._write_reg(_REG_MIC34_PWR, 0x0F)   # MIC3/4: bias+ADC+PGA power

        # 12. Enable device (start-up sequence)
        self._write_reg(_REG_RESET, 0x71)
        time.sleep_ms(10)
        self._write_reg(_REG_RESET, 0x41)
        time.sleep_ms(50)  # Allow ADC to stabilize

        # 13. Enable ADC clocks for all channels
        self._write_reg(_REG_CLK_OFF, 0x00)

        self._powered = True
        print("ES7210: initialized (16 kHz, 16-bit, I2S slave)")

    # ─── Public API ───────────────────────────────────────────────

    def set_mic_gain(self, db):
        """Set PGA gain in dB for all mic channels.

        Valid values: 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 34, 36, 37
        Rounds down to nearest valid value.
        """
        valid = sorted(_GAIN_TABLE.keys())
        best = valid[0]
        for v in valid:
            if v <= db:
                best = v
        code = 0x10 | _GAIN_TABLE[best]
        self._write_reg(_REG_MIC1_GAIN, code)
        self._write_reg(_REG_MIC2_GAIN, code)
        print(f"ES7210: mic gain set to {best} dB (reg=0x{code:02X})")

    def set_adc_volume(self, vol):
        """Set ADC digital volume for channels 1 & 2.

        Range: 0x00 = -95dB, 0xBF = 0dB, 0xFF = +32dB
        """
        self._write_reg(_REG_ADC1_DVOL, vol)
        self._write_reg(_REG_ADC2_DVOL, vol)

    def standby(self):
        """Power down ADC and stop MCLK."""
        if not self._powered:
            return
        # Power down all mic channels
        self._write_reg(_REG_MIC12_PWR, 0xFF)
        self._write_reg(_REG_MIC34_PWR, 0xFF)
        # Disable clocks
        self._write_reg(_REG_CLK_OFF, 0xFF)
        # Stop MCLK
        if self._mclk_pwm:
            self._mclk_pwm.deinit()
            self._mclk_pwm = None
        self._powered = False
        print("ES7210: standby")

    def resume(self):
        """Re-init after standby."""
        if self._powered:
            return
        self.init()

    def deinit(self):
        """Full shutdown."""
        self.standby()

    @property
    def is_powered(self):
        return self._powered
